import { ReactNode } from 'react';
import type { Metadata } from 'next';

import Header from '@/components/common/Header/Header';

// These styles apply to every route in the application
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>App</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
